'use client'
import {StyleSheet} from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
      backgroundColor: '#FFF',
      padding: "32 64",
      fontFamily: 'Roboto',
      // fontFamily: 'Arial',
      fontSize: 12,
    },
    header: {
      fontSize: 11,
      borderBottom: "1px solid black",
      paddingBottom: "4px",
    },
    title1: {
      marginTop: "32px",
      fontSize: 11,
      fontStyle: "bold",
    },
    title2: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      textAlign: "center",
      fontSize: 14,
      fontStyle: "bold",
      width: "100%",
      border: "1px solid #000",
      backgroundColor: "#DDD",
    },
    disclaimerClient: {
      width: "126px",
      fontSize: 8,
      borderBottom: "1px solid #000",
      marginTop: "8px",
      marginBottom: "4px",
    },
    disclaimerSubcontractor: {
      width: "130px",
      fontSize: 8,
      borderBottom: "1px solid #000",
      marginTop: "8px",
      marginBottom: "4px",
    },
    normal: {
      fontSize: 10,
    },
    disclaimer: {
      fontSize: 10,
      marginTop: "32px",
    },
    normalBold: {
      fontSize: 10,
      fontStyle: "bold",
    },
    signaturesWrapper: {
      marginTop: "16px",
      display: 'flex',
      flexDirection: "row",
      justifyContent: "space-between",
    },
    singleSignature: {
      display: "flex",
      justifyContent: "flex-end",
      alignItems: "center",
      margin: "8px 0",
      padding: "2px",
      width: "31%",
    },
    signatureValue: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      padding: "2px",
      fontSize: 10,
      // fontStyle: "italic",
    },
    signatureLabel: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      padding: "2px",
      borderTop: "1px solid black",
      borderBottom: "1px solid black",
    },
    signatureLabelText: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      fontSize: 8,
      // fontStyle: "italic",
    },
    flex: {
      display: 'flex',
      marginTop: 6,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    table: {
      borderStyle: 'solid',
      borderWidth: 1,
      borderRightWidth: 0,
      borderBottomWidth: 0,
    },
    tableRow: {
      flexDirection: 'row',
    },
    tableCol1: {
      width: "20%",
      borderStyle: 'solid',
      borderWidth: 1,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      paddingLeft: 4,
      backgroundColor: "#DDD",
    },
    tableCol2: {
      width: "80%",
      borderStyle: 'solid',
      borderWidth: 1,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      paddingLeft: 4,
    },
    halfTablesContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: "16px",
    },
    halfTable1: {
      borderStyle: 'solid',
      borderWidth: 1,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      marginRight: "8px",
      width: "110%",
    },
    halfTable2: {
      borderStyle: 'solid',
      borderWidth: 1,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      marginLeft: "8px",
    },
    halfTableRow: {
      flexDirection: 'row',
      height: "25px",
    },
    halfTableHeader: {
      display: "flex",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      backgroundColor: "#DDD",
      borderBottom: "1px solid #000",
      borderRight: "1px solid #000",
    },
    halfTableHeaderText: {
      fontSize: 9,
      fontStyle: "bold",
      textAlign: "center",
    },
    halfTableCol1: {
      width: "30%",
      borderStyle: 'solid',
      borderWidth: 1,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      paddingLeft: 4,
      backgroundColor: "#DDD",
    },
    halfTableCol2: {
      width: "70%",
      borderStyle: 'solid',
      borderWidth: 1,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      paddingLeft: 4,
    },
    normalEmail: {
      fontSize: 9,
    }
  });