name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: B2B-PDFs-win
            artifact_directory: dist/*.exe
          - os: macos-latest
            artifact_name: B2B-PDFs-mac
            artifact_directory: dist/*.dmg
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install
        run: >-
          yarn install
      - name: Build release
        run: >-
           yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_directory }}
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: $GITHUB_WORKSPACE/artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "$GITHUB_WORKSPACE/artifacts/B2B-PDFs-win/*,$GITHUB_WORKSPACE/artifacts/B2B-PDFs-mac/*"
        
